import { describe, it, expect } from 'vitest'
import { keyPaths, hydrateLocale } from '../hydrate.js'
import en from '../en.json'
// Generated by scripts/build-locale-values.mjs's pretest hook -- see the
// import comment in locale-parity.test.js for why parity itself is checked
// against source/ instead.
import esValues from '../es.json'
import frValues from '../fr.json'
import huValues from '../hu.json'
import esSource from '../source/es.json'
import frSource from '../source/fr.json'
import huSource from '../source/hu.json'

describe('keyPaths', () => {
  it('walks nested objects depth-first in insertion order', () => {
    expect(keyPaths({ b: { y: 1, x: 2 }, a: 3 })).toEqual(['b.y', 'b.x', 'a'])
  })
})

describe('hydrateLocale', () => {
  it('rebuilds a nested dictionary from a flat values array', () => {
    const shape = { greeting: 'hi', nested: { a: 1, b: 2 } }
    const values = ['bonjour', 10, 20]
    expect(hydrateLocale(shape, values)).toEqual({ greeting: 'bonjour', nested: { a: 10, b: 20 } })
  })
})

describe('locale build round trip', () => {
  // This is the guard for the actual size-saving change: es/fr/hu ship as
  // position-encoded arrays (build-locale-values.mjs) and get reassembled
  // into a real dictionary at load time (index.js). If either side's key
  // traversal order drifts, values silently land under the wrong key -- this
  // catches that by reconstructing the full dictionary and diffing it
  // against the human-maintained source, not just checking array lengths.
  for (const [name, values, source] of [
    ['es', esValues, esSource],
    ['fr', frValues, frSource],
    ['hu', huValues, huSource],
  ]) {
    it(`${name}.json rehydrates to exactly source/${name}.json`, () => {
      expect(hydrateLocale(en, values)).toEqual(source)
    })
  }
})
